### PR TITLE
Handle tables with custom `fillfactor` + add tests + add CI

### LINKED ISSUE #45: Issues with fillfactor
[This lambda](https://github.com/lfittl/activerecord-clean-db-structure/blob/de75f003fda2ca5a635aa2dd2d57f9661f404c64/lib/activerecord-clean-db-structure/clean_dump.rb#L139) is crashing where a table with a `fillfactor` exists.

Consider these two tables:

```sql
CREATE TABLE foo (
    id integer NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
)
WITH (fillfactor='85');

CREATE TABLE bar (
    id integer NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
);
```

The check [here](https://github.com/lfittl/activerecord-clean-db-structure/blob/de75f003fda2ca5a635aa2dd2d57f9661f404c64/lib/activerecord-clean-db-structure/clean_dump.rb#L151) won't detect the end of the table definition for `foo`.

This is only an issue when `order_column_definitions` is turned on. I'll send a PR.

### PR DESCRIPTION
**Pull request by ghiculescu**
Fix: https://github.com/lfittl/activerecord-clean-db-structure/issues/45

### CODE REVIEW

File: lib/activerecord-clean-db-structure/clean_dump.rb [hunk 1]
```diff
@@ -124,7 +124,7 @@ def run
         dump.gsub!(/^CREATE( UNIQUE)? INDEX \w+ ON .+\n+/, '')
         dump.gsub!(/^-- Name: \w+; Type: INDEX\n+/, '')
         indexes.each do |table, indexes_for_table|
-          dump.gsub!(/^(CREATE TABLE #{table}\b(:?[^;\n]*\n)+\);\n)/) { $1 + "\n" + indexes_for_table }
+          dump.gsub!(/^(CREATE TABLE #{table}\b(:?[^;\n]*\n)+\);*\n(?:.*);*)/) { $1 + "\n" + indexes_for_table }
```
Comment (andyatkinson) [inline lib/activerecord-clean-db-structure/clean_dump.rb]: Since this was already complex and is getting more complex, it would be nice if this regex could live as a variable and have a corresponding Ruby class that runs a test with the different table structure DDL dump variations you mentioned. 

For example one without a fillfactor or other table params, and one with that set. 

If you agree, maybe we could capture that in an issue for now, if you don't have time for the unit test now, and have tested this manually and it's working for you.

**Comment by andyatkinson** [comment]
Seems ok to me. Any concerns @lfittl? If not, we can merge this, then add it to a new candidate release: https://github.com/lfittl/activerecord-clean-db-structure/pull/47

File: lib/activerecord-clean-db-structure/clean_dump.rb [hunk 2]
```diff
@@ -151,7 +151,7 @@ def order_column_definitions(source)
           inside_table = true
           columns = []
           result << source_line
-        elsif source_line.start_with?(");")
+        elsif source_line.start_with?(")")
```
Comment (ghiculescu) [inline lib/activerecord-clean-db-structure/clean_dump.rb:154]: Test fails without this fix:

image

File: lib/activerecord-clean-db-structure/clean_dump.rb [hunk 3]
```diff
@@ -124,7 +124,7 @@ def run
         dump.gsub!(/^CREATE( UNIQUE)? INDEX \w+ ON .+\n+/, '')
         dump.gsub!(/^-- Name: \w+; Type: INDEX\n+/, '')
         indexes.each do |table, indexes_for_table|
-          dump.gsub!(/^(CREATE TABLE #{table}\b(:?[^;\n]*\n)+\);\n)/) { $1 + "\n" + indexes_for_table }
+          dump.gsub!(/^(CREATE TABLE #{table}\b(:?[^;\n]*\n)+\);*\n(?:.*);*)/) { $1 + "\n\n" + indexes_for_table }
```
Comment (ghiculescu) [inline lib/activerecord-clean-db-structure/clean_dump.rb:127]: Test fails without this fix:

image

**Comment by ghiculescu** [comment]
I think you will need to enable github actions on this repo for the tests to run on PRs. It might only work after this is merged.

**Comment by andyatkinson** [comment]
Looks really good on a quick initial read. I'll let @lfittl chime in. Nice work!

**Comment by andyatkinson** [comment]
@ghiculescu I don't have the "settings" tab access where I'd expect to enable GH actions. Maybe @lfittl can do that.

I did grab your branch and ran `bundle exec rake test` locally, and it looks good. Let's merge.
